"use client";
import { useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import { Button, Card, Field, Input, Stat } from "@/components/ui";
export default function UtilityTools(){
 const mode=usePathname().split("/").pop(); const [a,setA]=useState("2000-01-01"),[b,setB]=useState(new Date().toISOString().slice(0,10)),[text,setText]=useState("2026"),[grades,setGrades]=useState("4, 3.5, 3, 4"),[credits,setCredits]=useState("3, 3, 2, 3");
 const out=useMemo(()=>{if(mode==="kalkulator-usia"){const x=new Date(a),y=new Date(b);let years=y.getFullYear()-x.getFullYear(),months=y.getMonth()-x.getMonth(),days=y.getDate()-x.getDate();if(days<0){months--;days+=new Date(y.getFullYear(),y.getMonth(),0).getDate()}if(months<0){years--;months+=12}return [`${Math.max(0,years)} tahun, ${Math.max(0,months)} bulan, ${Math.max(0,days)} hari`,`Tanggal lahir ${a}`]}if(mode==="angka-romawi"){const n=Math.max(1,Math.min(3999,Number(text)||1));let v=n,s="";for(const [x,r] of [[1000,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]] as [number,string][])while(v>=x){s+=r;v-=x}return [s,`Angka ${n}`]}const g=grades.split(/[,\s]+/).map(Number),c=credits.split(/[,\s]+/).map(Number),total=c.reduce((x,y)=>x+y,0);return [(g.reduce((x,y,i)=>x+y*(c[i]||0),0)/total||0).toFixed(2),`${total} SKS`]},[mode,a,b,text,grades,credits]);
 return <div className="grid gap-4 lg:grid-cols-[1fr_.8fr]"><Card title={mode==="kalkulator-usia"?"Kalkulator Usia":mode==="angka-romawi"?"Konverter Angka Romawi":"Kalkulator IPK"}><div className="grid gap-4 sm:grid-cols-2">{mode==="kalkulator-usia"?<><Field label="Tanggal lahir"><Input type="date" value={a} onChange={e=>setA(e.target.value)}/></Field><Field label="Hitung sampai"><Input type="date" value={b} onChange={e=>setB(e.target.value)}/></Field></>:mode==="angka-romawi"?<Field label="Angka (1–3999)"><Input value={text} onChange={e=>setText(e.target.value)} inputMode="numeric"/></Field>:<><Field label="Nilai mutu (pisahkan koma/spasi)"><Input value={grades} onChange={e=>setGrades(e.target.value)}/></Field><Field label="SKS masing-masing"><Input value={credits} onChange={e=>setCredits(e.target.value)}/></Field></>}</div><Button className="mt-5">Hitung</Button></Card><Card title="Hasil"><Stat label={mode==="angka-romawi"?"Romawi":mode==="kalkulator-usia"?"Usia":"IPK"} value={out[0]} sub={out[1]}/></Card></div>;
}
